import { MigrationInterface, QueryRunner } from "typeorm";

export class UpdatedSchema1741938999570 implements MigrationInterface {
    name = 'UpdatedSchema1741938999570'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_3d6915a33798152a079997cad28"`);
        await queryRunner.query(`ALTER TABLE "organization_departments_department" DROP CONSTRAINT "FK_87a23080e0b842ebccc0f827045"`);
        await queryRunner.query(`ALTER TABLE "department" DROP CONSTRAINT "FK_a79485f797e2f72cf4a32fac263"`);
        await queryRunner.query(`ALTER TABLE "department" DROP CONSTRAINT "PK_9a2213262c1593bffb581e382f5"`);
        await queryRunner.query(`ALTER TABLE "department" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "department" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "department" ADD CONSTRAINT "PK_9a2213262c1593bffb581e382f5" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "department" DROP COLUMN "superAdminId"`);
        await queryRunner.query(`ALTER TABLE "department" ADD "superAdminId" integer`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_dfda472c0af7812401e592b6a61"`);
        await queryRunner.query(`ALTER TABLE "organization_departments_department" DROP CONSTRAINT "FK_52635efa09515ed5950679f1898"`);
        await queryRunner.query(`ALTER TABLE "organization" DROP CONSTRAINT "FK_a879ed0435f36abdefa70062817"`);
        await queryRunner.query(`ALTER TABLE "organization" DROP CONSTRAINT "PK_472c1f99a32def1b0abb219cd67"`);
        await queryRunner.query(`ALTER TABLE "organization" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "organization" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organization" ADD CONSTRAINT "PK_472c1f99a32def1b0abb219cd67" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "organization" DROP COLUMN "superAdminId"`);
        await queryRunner.query(`ALTER TABLE "organization" ADD "superAdminId" integer`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_d33425a4fb8f9004113762e7104"`);
        await queryRunner.query(`ALTER TABLE "super_admin" DROP CONSTRAINT "PK_3c4fab866f4c62a54ee1ebb1fe3"`);
        await queryRunner.query(`ALTER TABLE "super_admin" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "super_admin" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "super_admin" ADD CONSTRAINT "PK_3c4fab866f4c62a54ee1ebb1fe3" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "task" DROP CONSTRAINT "FK_91d76dd2ae372b9b7dfb6bf3fd2"`);
        await queryRunner.query(`ALTER TABLE "task_assigned_users_user" DROP CONSTRAINT "FK_876e3650ef1a751f8e9b88d4510"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "PK_cace4a159ff9f2512dd42373760"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "superAdminId"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "superAdminId" integer`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "organizationId"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "organizationId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "departmentId"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "departmentId" integer`);
        await queryRunner.query(`ALTER TABLE "task_assigned_users_user" DROP CONSTRAINT "FK_1b1a0ee8b85e614fe21107e0fb8"`);
        await queryRunner.query(`ALTER TABLE "task" DROP CONSTRAINT "PK_fb213f79ee45060ba925ecd576e"`);
        await queryRunner.query(`ALTER TABLE "task" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "task" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "task" ADD CONSTRAINT "PK_fb213f79ee45060ba925ecd576e" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "task" DROP COLUMN "createdById"`);
        await queryRunner.query(`ALTER TABLE "task" ADD "createdById" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organization_departments_department" DROP CONSTRAINT "PK_797dc762071e22f92c3a6e788fa"`);
        await queryRunner.query(`ALTER TABLE "organization_departments_department" ADD CONSTRAINT "PK_87a23080e0b842ebccc0f827045" PRIMARY KEY ("departmentId")`);
        await queryRunner.query(`DROP INDEX "public"."IDX_52635efa09515ed5950679f189"`);
        await queryRunner.query(`ALTER TABLE "organization_departments_department" DROP COLUMN "organizationId"`);
        await queryRunner.query(`ALTER TABLE "organization_departments_department" ADD "organizationId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organization_departments_department" DROP CONSTRAINT "PK_87a23080e0b842ebccc0f827045"`);
        await queryRunner.query(`ALTER TABLE "organization_departments_department" ADD CONSTRAINT "PK_797dc762071e22f92c3a6e788fa" PRIMARY KEY ("departmentId", "organizationId")`);
        await queryRunner.query(`ALTER TABLE "organization_departments_department" DROP CONSTRAINT "PK_797dc762071e22f92c3a6e788fa"`);
        await queryRunner.query(`ALTER TABLE "organization_departments_department" ADD CONSTRAINT "PK_52635efa09515ed5950679f1898" PRIMARY KEY ("organizationId")`);
        await queryRunner.query(`DROP INDEX "public"."IDX_87a23080e0b842ebccc0f82704"`);
        await queryRunner.query(`ALTER TABLE "organization_departments_department" DROP COLUMN "departmentId"`);
        await queryRunner.query(`ALTER TABLE "organization_departments_department" ADD "departmentId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organization_departments_department" DROP CONSTRAINT "PK_52635efa09515ed5950679f1898"`);
        await queryRunner.query(`ALTER TABLE "organization_departments_department" ADD CONSTRAINT "PK_797dc762071e22f92c3a6e788fa" PRIMARY KEY ("organizationId", "departmentId")`);
        await queryRunner.query(`ALTER TABLE "task_assigned_users_user" DROP CONSTRAINT "PK_42062be7c481afd8e850318f790"`);
        await queryRunner.query(`ALTER TABLE "task_assigned_users_user" ADD CONSTRAINT "PK_876e3650ef1a751f8e9b88d4510" PRIMARY KEY ("userId")`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1b1a0ee8b85e614fe21107e0fb"`);
        await queryRunner.query(`ALTER TABLE "task_assigned_users_user" DROP COLUMN "taskId"`);
        await queryRunner.query(`ALTER TABLE "task_assigned_users_user" ADD "taskId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "task_assigned_users_user" DROP CONSTRAINT "PK_876e3650ef1a751f8e9b88d4510"`);
        await queryRunner.query(`ALTER TABLE "task_assigned_users_user" ADD CONSTRAINT "PK_42062be7c481afd8e850318f790" PRIMARY KEY ("userId", "taskId")`);
        await queryRunner.query(`ALTER TABLE "task_assigned_users_user" DROP CONSTRAINT "PK_42062be7c481afd8e850318f790"`);
        await queryRunner.query(`ALTER TABLE "task_assigned_users_user" ADD CONSTRAINT "PK_1b1a0ee8b85e614fe21107e0fb8" PRIMARY KEY ("taskId")`);
        await queryRunner.query(`DROP INDEX "public"."IDX_876e3650ef1a751f8e9b88d451"`);
        await queryRunner.query(`ALTER TABLE "task_assigned_users_user" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "task_assigned_users_user" ADD "userId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "task_assigned_users_user" DROP CONSTRAINT "PK_1b1a0ee8b85e614fe21107e0fb8"`);
        await queryRunner.query(`ALTER TABLE "task_assigned_users_user" ADD CONSTRAINT "PK_42062be7c481afd8e850318f790" PRIMARY KEY ("taskId", "userId")`);
        await queryRunner.query(`CREATE INDEX "IDX_52635efa09515ed5950679f189" ON "organization_departments_department" ("organizationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_87a23080e0b842ebccc0f82704" ON "organization_departments_department" ("departmentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1b1a0ee8b85e614fe21107e0fb" ON "task_assigned_users_user" ("taskId") `);
        await queryRunner.query(`CREATE INDEX "IDX_876e3650ef1a751f8e9b88d451" ON "task_assigned_users_user" ("userId") `);
        await queryRunner.query(`ALTER TABLE "department" ADD CONSTRAINT "FK_a79485f797e2f72cf4a32fac263" FOREIGN KEY ("superAdminId") REFERENCES "super_admin"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization" ADD CONSTRAINT "FK_a879ed0435f36abdefa70062817" FOREIGN KEY ("superAdminId") REFERENCES "super_admin"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_d33425a4fb8f9004113762e7104" FOREIGN KEY ("superAdminId") REFERENCES "super_admin"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_dfda472c0af7812401e592b6a61" FOREIGN KEY ("organizationId") REFERENCES "organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_3d6915a33798152a079997cad28" FOREIGN KEY ("departmentId") REFERENCES "department"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task" ADD CONSTRAINT "FK_91d76dd2ae372b9b7dfb6bf3fd2" FOREIGN KEY ("createdById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_departments_department" ADD CONSTRAINT "FK_52635efa09515ed5950679f1898" FOREIGN KEY ("organizationId") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "organization_departments_department" ADD CONSTRAINT "FK_87a23080e0b842ebccc0f827045" FOREIGN KEY ("departmentId") REFERENCES "department"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_assigned_users_user" ADD CONSTRAINT "FK_1b1a0ee8b85e614fe21107e0fb8" FOREIGN KEY ("taskId") REFERENCES "task"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "task_assigned_users_user" ADD CONSTRAINT "FK_876e3650ef1a751f8e9b88d4510" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "task_assigned_users_user" DROP CONSTRAINT "FK_876e3650ef1a751f8e9b88d4510"`);
        await queryRunner.query(`ALTER TABLE "task_assigned_users_user" DROP CONSTRAINT "FK_1b1a0ee8b85e614fe21107e0fb8"`);
        await queryRunner.query(`ALTER TABLE "organization_departments_department" DROP CONSTRAINT "FK_87a23080e0b842ebccc0f827045"`);
        await queryRunner.query(`ALTER TABLE "organization_departments_department" DROP CONSTRAINT "FK_52635efa09515ed5950679f1898"`);
        await queryRunner.query(`ALTER TABLE "task" DROP CONSTRAINT "FK_91d76dd2ae372b9b7dfb6bf3fd2"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_3d6915a33798152a079997cad28"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_dfda472c0af7812401e592b6a61"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_d33425a4fb8f9004113762e7104"`);
        await queryRunner.query(`ALTER TABLE "organization" DROP CONSTRAINT "FK_a879ed0435f36abdefa70062817"`);
        await queryRunner.query(`ALTER TABLE "department" DROP CONSTRAINT "FK_a79485f797e2f72cf4a32fac263"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_876e3650ef1a751f8e9b88d451"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1b1a0ee8b85e614fe21107e0fb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_87a23080e0b842ebccc0f82704"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_52635efa09515ed5950679f189"`);
        await queryRunner.query(`ALTER TABLE "task_assigned_users_user" DROP CONSTRAINT "PK_42062be7c481afd8e850318f790"`);
        await queryRunner.query(`ALTER TABLE "task_assigned_users_user" ADD CONSTRAINT "PK_1b1a0ee8b85e614fe21107e0fb8" PRIMARY KEY ("taskId")`);
        await queryRunner.query(`ALTER TABLE "task_assigned_users_user" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "task_assigned_users_user" ADD "userId" uuid NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_876e3650ef1a751f8e9b88d451" ON "task_assigned_users_user" ("userId") `);
        await queryRunner.query(`ALTER TABLE "task_assigned_users_user" DROP CONSTRAINT "PK_1b1a0ee8b85e614fe21107e0fb8"`);
        await queryRunner.query(`ALTER TABLE "task_assigned_users_user" ADD CONSTRAINT "PK_42062be7c481afd8e850318f790" PRIMARY KEY ("userId", "taskId")`);
        await queryRunner.query(`ALTER TABLE "task_assigned_users_user" DROP CONSTRAINT "PK_42062be7c481afd8e850318f790"`);
        await queryRunner.query(`ALTER TABLE "task_assigned_users_user" ADD CONSTRAINT "PK_876e3650ef1a751f8e9b88d4510" PRIMARY KEY ("userId")`);
        await queryRunner.query(`ALTER TABLE "task_assigned_users_user" DROP COLUMN "taskId"`);
        await queryRunner.query(`ALTER TABLE "task_assigned_users_user" ADD "taskId" uuid NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_1b1a0ee8b85e614fe21107e0fb" ON "task_assigned_users_user" ("taskId") `);
        await queryRunner.query(`ALTER TABLE "task_assigned_users_user" DROP CONSTRAINT "PK_876e3650ef1a751f8e9b88d4510"`);
        await queryRunner.query(`ALTER TABLE "task_assigned_users_user" ADD CONSTRAINT "PK_42062be7c481afd8e850318f790" PRIMARY KEY ("taskId", "userId")`);
        await queryRunner.query(`ALTER TABLE "organization_departments_department" DROP CONSTRAINT "PK_797dc762071e22f92c3a6e788fa"`);
        await queryRunner.query(`ALTER TABLE "organization_departments_department" ADD CONSTRAINT "PK_52635efa09515ed5950679f1898" PRIMARY KEY ("organizationId")`);
        await queryRunner.query(`ALTER TABLE "organization_departments_department" DROP COLUMN "departmentId"`);
        await queryRunner.query(`ALTER TABLE "organization_departments_department" ADD "departmentId" uuid NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_87a23080e0b842ebccc0f82704" ON "organization_departments_department" ("departmentId") `);
        await queryRunner.query(`ALTER TABLE "organization_departments_department" DROP CONSTRAINT "PK_52635efa09515ed5950679f1898"`);
        await queryRunner.query(`ALTER TABLE "organization_departments_department" ADD CONSTRAINT "PK_797dc762071e22f92c3a6e788fa" PRIMARY KEY ("departmentId", "organizationId")`);
        await queryRunner.query(`ALTER TABLE "organization_departments_department" DROP CONSTRAINT "PK_797dc762071e22f92c3a6e788fa"`);
        await queryRunner.query(`ALTER TABLE "organization_departments_department" ADD CONSTRAINT "PK_87a23080e0b842ebccc0f827045" PRIMARY KEY ("departmentId")`);
        await queryRunner.query(`ALTER TABLE "organization_departments_department" DROP COLUMN "organizationId"`);
        await queryRunner.query(`ALTER TABLE "organization_departments_department" ADD "organizationId" uuid NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_52635efa09515ed5950679f189" ON "organization_departments_department" ("organizationId") `);
        await queryRunner.query(`ALTER TABLE "organization_departments_department" DROP CONSTRAINT "PK_87a23080e0b842ebccc0f827045"`);
        await queryRunner.query(`ALTER TABLE "organization_departments_department" ADD CONSTRAINT "PK_797dc762071e22f92c3a6e788fa" PRIMARY KEY ("organizationId", "departmentId")`);
        await queryRunner.query(`ALTER TABLE "task" DROP COLUMN "createdById"`);
        await queryRunner.query(`ALTER TABLE "task" ADD "createdById" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "task" DROP CONSTRAINT "PK_fb213f79ee45060ba925ecd576e"`);
        await queryRunner.query(`ALTER TABLE "task" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "task" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "task" ADD CONSTRAINT "PK_fb213f79ee45060ba925ecd576e" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "task_assigned_users_user" ADD CONSTRAINT "FK_1b1a0ee8b85e614fe21107e0fb8" FOREIGN KEY ("taskId") REFERENCES "task"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "departmentId"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "departmentId" uuid`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "organizationId"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "organizationId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "superAdminId"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "superAdminId" uuid`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "PK_cace4a159ff9f2512dd42373760"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "task_assigned_users_user" ADD CONSTRAINT "FK_876e3650ef1a751f8e9b88d4510" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task" ADD CONSTRAINT "FK_91d76dd2ae372b9b7dfb6bf3fd2" FOREIGN KEY ("createdById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "super_admin" DROP CONSTRAINT "PK_3c4fab866f4c62a54ee1ebb1fe3"`);
        await queryRunner.query(`ALTER TABLE "super_admin" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "super_admin" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "super_admin" ADD CONSTRAINT "PK_3c4fab866f4c62a54ee1ebb1fe3" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_d33425a4fb8f9004113762e7104" FOREIGN KEY ("superAdminId") REFERENCES "super_admin"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization" DROP COLUMN "superAdminId"`);
        await queryRunner.query(`ALTER TABLE "organization" ADD "superAdminId" uuid`);
        await queryRunner.query(`ALTER TABLE "organization" DROP CONSTRAINT "PK_472c1f99a32def1b0abb219cd67"`);
        await queryRunner.query(`ALTER TABLE "organization" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "organization" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "organization" ADD CONSTRAINT "PK_472c1f99a32def1b0abb219cd67" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "organization" ADD CONSTRAINT "FK_a879ed0435f36abdefa70062817" FOREIGN KEY ("superAdminId") REFERENCES "super_admin"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_departments_department" ADD CONSTRAINT "FK_52635efa09515ed5950679f1898" FOREIGN KEY ("organizationId") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_dfda472c0af7812401e592b6a61" FOREIGN KEY ("organizationId") REFERENCES "organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "department" DROP COLUMN "superAdminId"`);
        await queryRunner.query(`ALTER TABLE "department" ADD "superAdminId" uuid`);
        await queryRunner.query(`ALTER TABLE "department" DROP CONSTRAINT "PK_9a2213262c1593bffb581e382f5"`);
        await queryRunner.query(`ALTER TABLE "department" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "department" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "department" ADD CONSTRAINT "PK_9a2213262c1593bffb581e382f5" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "department" ADD CONSTRAINT "FK_a79485f797e2f72cf4a32fac263" FOREIGN KEY ("superAdminId") REFERENCES "super_admin"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_departments_department" ADD CONSTRAINT "FK_87a23080e0b842ebccc0f827045" FOREIGN KEY ("departmentId") REFERENCES "department"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_3d6915a33798152a079997cad28" FOREIGN KEY ("departmentId") REFERENCES "department"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
